variables:
  IMAGE_NAME: jinyhehe/spacestory
  IMAGE_TAG: "1.0"

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 13.209.19.192 >> ~/.ssh/known_hosts
  script:
    - ssh -i $SSH_KEY ubuntu@13.209.19.192 "echo $DOCKER_REGISTRY_PASS | docker login --username $DOCKER_REGISTRY_USER --password-stdin && docker rm spring-app -f || true && docker rmi $IMAGE_NAME:$IMAGE_TAG || true && docker pull $IMAGE_NAME:$IMAGE_TAG && docker run -d -p 8080:8080 --name spring-app $IMAGE_NAME:$IMAGE_TAG"
  tags:
    - deploy
