compile:
  stage: compile
  before_script: 
    - export PATH="/home/ubuntu/.sdkman/candidates/gradle/current/bin:$PATH"
  script:
    - ls
    - echo $ENV_YML > env.yml
    - ls
  tags:
    - compile
    