spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console.enabled: true
