spring:
  application:
    name: SpaceStory

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: 0X6PaMWszFEfdk5uHyit
            client-secret: ${OAUTH2_NAVER_SECRET_KEY}
            redirect-uri: https://spacestory.duckdns.org/login/oauth2/code/naver
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-name: kakao
            client-id: 355a2e7f42dfd28fae09a13c55db702e
            client-secret: ${OAUTH2_KAKAO_SECRET_KEY}
            redirect-uri: https://spacestory.duckdns.org/login/oauth2/code/kakao
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
          google:
            client-name: google
            client-id: 15683748038-kndmsc37419grhklg27ra02qogmsc98a.apps.googleusercontent.com
            client-secret: ${OAUTH2_GOOGLE_SECRET_KEY}
            redirect-uri: https://spacestory.duckdns.org/login/oauth2/code/google
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

jwt:
  secretKey: ${JWT_SECRET_KEY}


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG