package com.juny.spacestory.space.domain;

public enum DetailedType {
  PARTY_ROOM,
  RESIDENCE,
  CAFE,
  PERFORMANCE_VENUE,
  CONFERENCE_HALL,
  EXHIBITION_HALL,
  STUDY_ROOM,
  LECTURE_ROOM,
  SEMINAR_ROOM,
  MEETING_ROOM,
  DANCE_ROOM,
  VOCAL_ROOM,
  INSTRUMENT_ROOM,
  DRAWING_ROOM,
  CRAFT_ROOM,
  BADMINTON_COURT,
  FUTSAL_COURT,
  TENNIS_COURT,
  FILM_STUDIO,
  BROADCAST_ROOM;
}
